version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: spring-rabbimq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "local"
      RABBITMQ_DEFAULT_PASS: "1234"