### notify pub ok
POST http://localhost:8080/notify/normal
Content-Type: application/x-www-form-urlencoded

### notify pub error
POST http://localhost:8080/notify/error
Content-Type: application/x-www-form-urlencoded

### dead-notify sub
POST http://localhost:8081/dead-notify/0
Content-Type: application/x-www-form-urlencoded
