### start
POST http://localhost:8080/push/test
Content-Type: application/x-www-form-urlencoded

message=샤쿠

### stop
DELETE http://localhost:8080/push/test

### start
POST http://localhost:8080/retry-push/test2
Content-Type: application/x-www-form-urlencoded

message=장애

### stop
DELETE http://localhost:8080/retry-push/test2


### retry effect on
PUT http://localhost:8081/retry/push/ON

### retry effect off
PUT http://localhost:8081/retry/push/OFF