# Develop or Default profile
debug: false
trace: false
logging:
  file:
    name: default.log
    path:
  logback:
    rollingpolicy:
      #      file-name-pattern:
      clean-history-on-start: false
      max-file-size: 10MB
      total-size-cap: 20GB
      max-history: 30
  level:
    org.springframework.web: info
    io.github.syakuis: trace
server:
  port: 8081
spring:
  main:
    banner-mode: console
  rabbitmq:
    host: localhost
    username: syaku
    password: 1234
    port: 5672
    connection-timeout: 0
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 2
          max-interval: 10s
          multiplier: 2