@startuml
participant "Producer" as pub
database "queue" as q1
participant "Consumer" as sub
database "dead-queue" as q2
participant "Dead Consumer" as sub2
participant "Slack Messenger" as msg

pub ->> q1
q1 ->> sub: auto ack
alt retry 3회
sub -x sub: 저장 오류
else retry 3회 진행 후
sub ->> q2: 오류가 발생된 queue 저장
end alt
q2 ->> sub2: no ack
sub2 -> sub2: 저장
alt error
sub2 -> sub2: retry 3회
else 재시도 만료
sub2 ->> msg: 메신저 알림
else 성공
q2 <<-- sub2: ack
end alt
@enduml